name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - name: Navigate to speciale directory (where the go.mod file is located)
      run: cd speciale

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
