name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print current directory
      run: pwd

    - name: List contents of speciale directory
      #print contents in current directory
      run: ls

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - name: Navigate to speciale directory
      run: cd speciale

    - name: List contents of speciale directory
      run: pwd

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Navigate back to root directory
      run: cd ..
