name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash
    working-directory: ./speciale

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: go build -v -o speciale ./...
      
    - name: Test
      run: go test -v ./...
